credit_risk/credit_risk/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('loan_admin/', include('loan_admin.urls')),
    path('loan_officer/', include('loan_officer.urls')),
    path('', include('login.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit_risk/loan_officer/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'loan_officer'
urlpatterns = [
	path('', views.index, name='index'),
	path('uploadCSV', views.uploadCSV, name='uploadCSV'),
	path('result', views.result, name='result'),
	path('add', views.addApplicant, name='add'),
	path('uploadCSV/?add=ok', views.uploadCSV, name='uploadCSV'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit_risk/login/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'login'
urlpatterns = [
	path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit_risk/loan_officer/models.py
from django.db import models
from dynamic_models.models import AbstractModelSchema, AbstractFieldSchema

# Create your models here.
class FieldSchema(AbstractFieldSchema):
    pass

class ModelSchema(AbstractModelSchema):
    pass

class FileUpload(models.Model):
	file = models.FileField(upload_to='credit_risk/dataset')

class SavedState(models.Model):
	stat = models.CharField(max_length=10)
	ml = models.CharField(max_length=10)
	statandml = models.CharField(max_length=10, default="false")

credit_risk/loan_officer/forms.py
import csv
import io
from django import forms
from django.forms import ModelForm
from django.db import connection
from django.db import models
import sys
from .models import ModelSchema, FieldSchema, FileUpload
from bootstrap4.widgets import RadioSelectButtonGroup

# class CSVForm(forms.Form):
# 	class Meta:
# 		model = CSV
# 		fields = '__all__'

# 	data_file = forms.FileField()

# 	def process_data(self):
# 		f = io.TextIOWrapper(self.cleaned_data['data_file'].file)
# 		reader = csv.DictReader(f)
# 		rest = [row for row in reader]
# 		if len(ModelSchema.objects.all()) != 0:
# 			applicant_model_schema = ModelSchema.objects.first()
# 		else:
# 			applicant_model_schema = ModelSchema.objects.create(name='LoanApplicant')
# 		field_schema = FieldSchema.objects.create(name='all_field', data_type='character')
# 		color = applicant_model_schema.add_field(
# 			field_schema,
# 			null = True,
# 		)
# 		LoanApplicant = applicant_model_schema.as_model()
# 		for j in rest:
# 			a = LoanApplicant(all_field=j)
# 			a.save()

class FileUploadForm(ModelForm):
	class Meta:
		model = FileUpload
		fields = '__all__'
	# def process_data(self, dict, f):
	# 	with open('id_dataset.csv', 'wb+') as destination:
	# 		for chunk in f.chunks():
	# 			destination.write(chunk)
	# 		destination.close()

class MyForm(forms.Form):
    # media_type = forms.ChoiceField(
    #     help_text="Select the order type.",
    #     required=True,
    #     label="Order Type:",
    #     widget=RadioSelectButtonGroup,
    #     choices=((1, 'Rule Based'), (2, 'Statistical based'), (3, 'ML based')),
    #     initial=1,
    # )
    loan_id = forms.CharField(max_length=100)
    rule_based = forms.BooleanField(required=False)
    statistical_based = forms.BooleanField(required=False)
    ML_based = forms.BooleanField(required=False)

credit_risk/loan_officer/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.db import models
from django.views.generic import FormView
from django.urls import reverse
from urllib.parse import urlencode
from .forms import MyForm, FileUploadForm
from .project import *
import sys
from .models import SavedState
import pickle
import codecs
from six.moves import cPickle
from loan_admin.models import UploadFile, Criteria, CriteriaHelper, Configuration

def index(request):
	form = MyForm()
	context = {'form':form}
	return render(request, 'loan_officer/index.html', context)
	# x = predict_score(columns, 'loan_status', nominal, "dataset.csv")
	# print(x.Preprocess())

def result(request):
	loan_id = request.GET.get('loan_id')
	rule = request.GET.get('rule_based')
	stat = request.GET.get('statistical_based')
	ml = request.GET.get('ML_based')
	res = ""
	columns = UploadFile.objects.all().first().columns.split(',')
	del columns[0]
	nominal = UploadFile.objects.all().first().nominal_features.split(',')
	if(SavedState.objects.all().first() == None):
		m = SavedState(stat="false", ml="false")
		m.save()
	if(rule and stat and ml):
		pass
	elif(rule and stat):
		pass
	elif(rule and ml):
		pass
	elif(stat and ml):
		if(SavedState.objects.all().first().statandml == "false"):
			learn_and_save("statandml", columns, nominal, "dataset.csv")
			m = SavedState.objects.all().first()
			m.statandml = "true"
			m.save()
		f = open('media/credit_risk/dataset/test_id_dataset.csv', 'r')
		line = f.readline()
		sp = line.split(',')
		count = 0
		while(line != ""):
			if(sp[0] == loan_id):
				break
			sp = line.split(',')
			line = f.readline()
		# if(sp[0] != int(loan_id)):
		del sp[0]
		del sp[0]
		res = load_and_predict("statandml", sp)
	elif(rule):
		f = open('test_id_rule_dataset.csv', 'r')
		line = f.readline()
		array = line.split(',')
		array[-1] = array[-1].replace('\n', '')
		print(array)
		Dict = {}
		for i in range(0, len(array)):
			Dict[array[i]] = i
		print(Dict)
		line = f.readline()
		while line != "":
			sp = line.split(',')
			if(sp[0] == loan_id):
				break
			line = f.readline()
		sp[-1] = sp[-1].replace('\n', '')
		print(sp)
		cri = Criteria.objects.all()
		conf = Configuration.objects.all()
		ans = 0
		for configuration in conf:
			for criteria in cri:
				helper = CriteriaHelper.objects.all().filter(criteria=criteria)
				truth = (criteria.feature == configuration.feature and criteria.product == configuration.product
					and criteria.category == configuration.category)
				print(truth)
				if(truth):
					print(criteria.data_source == '3')
					if(criteria.data_source == '3'): # for SQL
						feature = criteria.api.split(' ')[-1]
						print(feature)
					feature_score = 0
					for crhelper in helper:
						# For categorical
						tup = crhelper.entry.split(' ')
						if(tup[0] == "is"):
							print(sp[Dict[feature]])
							if(tup[1] == sp[Dict[feature]]):
								feature_score += crhelper.score
						elif(tup[0] == ">"):
							if(int(sp[Dict[feature]]) > int(tup[1])):
								feature_score += crhelper.score
						elif(tup[0] == "<"):
							if(int(sp[Dict[feature]]) < int(tup[1])):
								feature_score += crhelper.score
						elif(tup[0] == ">="):
							if(int(sp[Dict[feature]]) >= int(tup[1])):
								feature_score += crhelper.score
						elif(tup[0] == "<="):
							if(int(sp[Dict[feature]]) <= int(tup[1])):
								feature_score += crhelper.score
					ans += configuration.weightage * feature_score
		f.close()
	elif(stat):
		if(SavedState.objects.all().first().stat == "false"):
			learn_and_save("statistical", columns, nominal, "dataset.csv")
			m = SavedState.objects.all().first()
			m.stat = "true"
			m.save()
		f = open('media/credit_risk/dataset/test_id_dataset.csv', 'r')
		line = f.readline()
		sp = line.split(',')
		count = 0
		while(line != ""):
			if(sp[0] == loan_id):
				break
			sp = line.split(',')
			line = f.readline()
		# if(sp[0] != int(loan_id)):
		del sp[0]
		del sp[0]
		res = load_and_predict("statistical", sp)
	else:
		if(SavedState.objects.all().first().ml == "false"):
			learn_and_save("ml", columns, nominal, "dataset.csv")
			m = SavedState.objects.all().first()
			m.ml = "true"
			m.save()
		f = open('media/credit_risk/dataset/test_id_dataset.csv', 'r')
		line = f.readline()
		sp = line.split(',')
		count = 0
		while(line != ""):
			if(sp[0] == loan_id):
				break
			sp = line.split(',')
			line = f.readline()
		# if(sp[0] != int(loan_id)):
		f.close()
		del sp[0]
		del sp[0]
		res = load_and_predict("ml", sp)
	if(rule):
		context = {'stat':True,'ans':ans}
		return render(request, 'loan_officer/result.html', context)
	else:
		out = res.split(',')
		context = {'stat':False, 'approve': out[0], 'not_approve': out[1]}
		return render(request, 'loan_officer/result.html', context)

def uploadCSV(request):
	add = request.GET.get('add')
	form = FileUploadForm()
	context = {'form':form, 'add':add}
	return render(request, 'loan_officer/uploadCSV.html', context)

@require_POST
def addApplicant(request):
	form = FileUploadForm(request.POST, request.FILES)
	url = reverse('loan_officer:uploadCSV')
	if form.is_valid():
		# form.process_data(request.POST, request.FILES['file'])
		form.save()
		base_url = reverse('loan_officer:uploadCSV')
		query_string =  urlencode({'add': 'ok'})
		url = '{}?{}'.format(base_url, query_string)
	return redirect(url)

credit_risk/loan_officer/templates/loan_officer/index.html
{% load crispy_forms_tags %}
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<div class="container">
	<div class="row justify-content-center">
    	<div class="col-8">
			<img src="/media/credit_risk/logo.jpg">
			<a href="{% url 'login:index' %}"> Home </a>&nbsp&nbsp&nbsp
			<a href="{% url 'loan_officer:uploadCSV' %}"> Upload Dataset </a>
			<h1> Scorecard </h1>
			<form action="{% url 'loan_officer:result' %}" method="GET" role="form">
				{{ form|crispy }}
			    <input type="submit" value="Submit" class="btn btn-success">
			</form>
		</div>
	</div>
</div>

credit_risk/loan_officer/templates/loan_officer/result.html
{% load crispy_forms_tags %}
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<div class="container">
	<div class="row justify-content-center">
    	<div class="col-8">
			<img src="/media/credit_risk/logo.jpg">
			<a href="{% url 'login:index' %}"> Home </a>&nbsp&nbsp&nbsp
			<a href="{% url 'loan_officer:index' %}"> Scorecard </a>&nbsp &nbsp &nbsp
			<a href="{% url 'loan_officer:uploadCSV' %}"> Upload Dataset </a>
			<h1> Results </h1>
			<table>
				{% if stat %}
					<tr><td><b>Score: </b>{{ ans }}</td></tr>
				{% else %}
				<tr><td><b>Approve</b>&nbsp &nbsp</td><td>{{ approve }}</td></tr>
				<tr><td><b>Not Approve</b>&nbsp &nbsp</td><td>{{ not_approve }}</td></tr>
				{% endif %}
			</table>
		</div>
	</div>
</div>

credit_risk/loan_officer/templates/loan_officer/uploadCSV.html
{% load crispy_forms_tags %}
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<div class="container">
	<div class="row justify-content-center">
    	<div class="col-8">
			<img src="/media/credit_risk/logo.jpg">
			<a href="{% url 'login:index' %}"> Home </a>&nbsp&nbsp&nbsp
			<a href="{% url 'loan_officer:index' %}"> Scorecard </a>&nbsp &nbsp &nbsp
			<h1> Customer Dataset Upload </h1>
			<form action="{% url 'loan_officer:add' %}" method="POST" enctype= multipart/form-data>
				{% csrf_token %}
				{{ form.as_p }}
			    <input type="submit" value="Submit" class="btn btn-success">
			</form>
		</div>
	</div>
</div>