credit_risk/credit_risk/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('loan_admin/', include('loan_admin.urls')),
    path('loan_officer/', include('loan_officer.urls')),
    path('', include('login.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit_risk/loan_admin/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'loan_admin'
urlpatterns = [
	path('', views.index, name='index'),
	path('add', views.addFeature, name='add'),
	path('index/?add=ok1', views.index, name='index1'),
	path('configuration', views.configuration, name='configuration'),
	path('criteria', views.criteria, name='criteria'),
	path('weigh', views.addConfiguration, name='weigh'),
	path('addCriteria', views.addCriteria, name='cri'),
	path('configuration/?add1=ok2', views.configuration, name='configuration1'),
	path('criteria/?add2=ok3', views.criteria, name='criteria1'),
	path('uploadCSV', views.uploadCSV, name='uploadCSV'),
	path('uploadCSV/?add3=ok4', views.uploadCSV, name='uploadCSV1'),
	path('addApplicant', views.addApplicant, name='addApplicant'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit_risk/loan_officer/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'loan_officer'
urlpatterns = [
	path('', views.index, name='index'),
	path('uploadCSV', views.uploadCSV, name='uploadCSV'),
	path('result', views.result, name='result'),
	path('add', views.addApplicant, name='add'),
	path('uploadCSV/?add=ok', views.uploadCSV, name='uploadCSV'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit_risk/login/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'login'
urlpatterns = [
	path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit_risk/login/models.py
from django.db import models

# Create your models here.

credit_risk/login/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'login/index.html')

credit_risk/login/templates/login/index.html
{% load crispy_forms_tags %}
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<div class="container">
	<div class="row justify-content-center">
    	<div class="col-8">
			<img src="/media/credit_risk/logo.jpg">
			<h1> Login </h1>
			<a href="{% url 'loan_officer:index' %}"> Loan Officer </a><br>
			<a href="{% url 'loan_admin:index' %}"> Loan Administrator </a>
		</div>
	</div>
</div>