credit_risk/credit_risk/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('loan_admin/', include('loan_admin.urls')),
    path('loan_officer/', include('loan_officer.urls')),
    path('', include('login.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit_risk/loan_admin/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'loan_admin'
urlpatterns = [
	path('', views.index, name='index'),
	path('add', views.addFeature, name='add'),
	path('index/?add=ok1', views.index, name='index1'),
	path('configuration', views.configuration, name='configuration'),
	path('criteria', views.criteria, name='criteria'),
	path('weigh', views.addConfiguration, name='weigh'),
	path('addCriteria', views.addCriteria, name='cri'),
	path('configuration/?add1=ok2', views.configuration, name='configuration1'),
	path('criteria/?add2=ok3', views.criteria, name='criteria1'),
	path('uploadCSV', views.uploadCSV, name='uploadCSV'),
	path('uploadCSV/?add3=ok4', views.uploadCSV, name='uploadCSV1'),
	path('addApplicant', views.addApplicant, name='addApplicant'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit_risk/login/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'login'
urlpatterns = [
	path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit_risk/loan_admin/models.py
from django.db import models
from dynamic_models.models import AbstractModelSchema, AbstractFieldSchema
from django import forms
# Create your models here.
class FieldSchema(AbstractFieldSchema):
    pass

class ModelSchema(AbstractModelSchema):
    pass

class UploadFile(models.Model):
	file = models.FileField(upload_to='credit_risk/dataset')
	columns = models.CharField(max_length=1000000)
	nominal_features = models.CharField(max_length=1000000)
# Create your models here.
class Feature(models.Model):
	VALUE_CHOICES = [
		('Bi', 'Binary'),
		('No', 'Nominal'),
		('In', 'Interval'),
		('Ra', 'Ratio'),

	]
	DATA_CHOICES = [
		('Nu', 'Numeric'),
		('Ch', 'Character'),
		('Da', 'Date'),
	]
	CATEGORY_CHOICES = [
		('In', 'Individual'),
		('Co', 'Company'),
		('Cy', 'Country'),
	]
	name = models.CharField(max_length=100)
	value = models.CharField(max_length=10, choices=VALUE_CHOICES)
	data_type = models.CharField(max_length=10, choices=DATA_CHOICES)
	category = models.CharField(max_length=10, choices=CATEGORY_CHOICES)

	def __str__(self):
		return self.name

class Configuration(models.Model):
	# FEATURE_CHOICES = [
	# 	('In', 'Individual'),
	# 	('Co', 'Company'),
	# 	('Cy', 'Country'),
	# ]
	CATEGORY_CHOICES = [
		('In', 'Individual'),
		('Co', 'Company'),
		('Cy', 'Country'),
	]
	PRODUCT_CHOICES = [
		('Ag', 'Agricultural'),
		('Ho', 'Home'),
		('Pe', 'Personal'),
		('Ve', 'Vehicle'),
	]
	feature = models.CharField(max_length=100, null=True)
	category = models.CharField(max_length=10, choices=CATEGORY_CHOICES)
	product = models.CharField(max_length=10, choices=PRODUCT_CHOICES)
	weightage = models.FloatField()

	def __str__(self):
		return self.feature

class Criteria(models.Model):
	feature = models.CharField(max_length=100, null=True)
	category = models.CharField(max_length=10)
	product = models.CharField(max_length=10)
	data_source = models.CharField(max_length=10)
	api = models.CharField(max_length=10000)
	key = models.CharField(max_length=100)

class CriteriaHelper(models.Model):
	criteria = models.ForeignKey(Criteria, 
		on_delete=models.CASCADE,)
	entry = models.CharField(max_length=1000000)
	score = models.IntegerField()

credit_risk/loan_admin/forms.py
from django import forms
from .models import Feature
from .models import Configuration
from .models import ModelSchema, FieldSchema
from .models import UploadFile, Criteria, CriteriaHelper
import csv
import io
from bootstrap4.widgets import RadioSelectButtonGroup
from crispy_forms.helper import FormHelper

class FeatureForm(forms.ModelForm):
	class Meta:
		model = Feature
		fields = ['name', 'value', 'data_type', 'category']

class ConfigurationForm(forms.ModelForm):	
	def __init__(self, *args, **kwargs):
		super(ConfigurationForm, self).__init__(*args, **kwargs)
		x = Feature.objects.values('name')
		print(x)
		FEATURE_CHOICES = []
		a = '1'
		for i in x:
			b = (a, i['name'])
			FEATURE_CHOICES.append(b)
			a = a + '1'
		self.fields['feature'] = forms.ChoiceField(choices=FEATURE_CHOICES, required=True )
	class Meta:
		model = Configuration
		fields = '__all__'

class UploadFileForm(forms.ModelForm):
	file = forms.FileField()
	columns = forms.CharField( widget=forms.Textarea )
	nominal_features = forms.CharField( widget=forms.Textarea )
	class Meta:
		model = UploadFile
		fields = '__all__'
	def process_data(self, dict, f):
		if(UploadFile.objects.all().first() == None):
			m = UploadFile(file=f, columns=dict['columns'], nominal_features=dict['nominal_features'])
			m.save()
		else:
			m = UploadFile.objects.all().first()
			m.file = f
			m.columns = dict['columns']
			m.nominal_features = dict['nominal_features']
			m.save()
		fw = open('dataset.csv', 'w')
		# with open('train_id_dataset.csv', 'wb+') as destination:
		# 	for chunk in f.chunks():
		# 		destination.write(chunk)
		# 	destination.close()
		# f.seek(0)
		f.seek(0)
		line = f.readline()
		count = 0
		while(line != b''):
			line = line.decode('ASCII')
			flag = 0
			lout = ""
			print(line)
			for i in range(0, len(line)):
				if(flag == 1):
					lout = lout + line[i]
				if(line[i] == ','):
					flag = 1
			fw.write(lout)
			line = f.readline()
			count = count + 1
			# print(line)
		fw.close()

class CriteriaForm(forms.ModelForm):
	CATEGORY_CHOICES = [
		('In', 'Individual'),
		('Co', 'Company'),
		('Cy', 'Country'),
	]
	PRODUCT_CHOICES = [
		('Ag', 'Agricultural'),
		('Ho', 'Home'),
		('Pe', 'Personal'),
		('Ve', 'Vehicle'),
	]
	DATA_CHOICES = [
		('xm', 'XML'),
		('js', 'JSON'),
		('sq', 'SQL'),
	]
	category = forms.ChoiceField(label="Category",choices=CATEGORY_CHOICES)
	product = forms.ChoiceField(label="Product",choices=PRODUCT_CHOICES)
	data_source = forms.ChoiceField(
        help_text="Select the data source",
        required=True,
        label="Order Type:",
        widget=RadioSelectButtonGroup,
        choices=((1, 'XML'), (2, 'JSON'), (3, 'SQL')),
        initial=1,
    )
	api = forms.CharField(required=True, label="API/SQL")
	key = forms.CharField(required=False, label="Key")
	
	def __init__(self, *args, **kwargs):
		self.entry_count = 0
		super(CriteriaForm, self).__init__(*args, **kwargs)
		x = Feature.objects.values('name')
		FEATURE_CHOICES = []
		a = '1'
		for field in x:
			b = (a, field['name'])
			FEATURE_CHOICES.append(b)
			a = a + '1'
		self.fields['feature'] = forms.ChoiceField(choices=FEATURE_CHOICES, required=True )
		criterias = CriteriaHelper.objects.filter(
			criteria=self.instance
		)
		i = 0
		for i in range(0, len(criterias)):
			field_name = 'entry_' % (i,)
			f = 'score_' + str(i+1)
			str1 = "Criteria " + str(i+1)
			str2 = "Score " + str(i+1)
			self.entry_count += 1
			self.fields[field_name] = forms.CharField(label=str1,required=False)
			self.fields[f] = forms.CharField(label=str2,required=False)
			try:
				self.initial[field_name] = criterias[i].entry
				self.initial[f] = criterias[i].score
			except IndexError:
				self.initial[field_name] = ""
				self.initial[f] = ""
		field_name = 'entry_' + str(i+1)
		f = 'score_' + str(i+1)
		str1 = "Criteria " + str(i+1)
		str2 = "Score " + str(i+1)
		self.entry_count += 1
		self.fields[field_name] = forms.CharField(label=str1,required=False, 
			widget=forms.TextInput(attrs={'id':'new_entry'}))
		self.fields[f] = forms.CharField(label=str2,required=False, 
			widget=forms.TextInput(attrs={'id':'new_score'}))
		count = 1
		if(args):
			print(args[0])
			for key in args[0]:
				if(key[:5] == "entry"):
					count += 1
			print("count " + str(count))
			for i in range(1, count-1):
				field_name = 'entry_' + str(i+1)
				f = 'score_' + str(i+1)
				str1 = "Criteria " + str(i+1)
				str2 = "Score " + str(i+1)
				self.entry_count += 1
				self.fields[field_name] = forms.CharField(label=str1,required=False, 
					widget=forms.TextInput(attrs={'id':'new_entry'}))
				self.fields[f] = forms.CharField(label=str2,required=False, 
					widget=forms.TextInput(attrs={'id':'new_score'}))

	def clean(self):
		entries = []
		i = 1
		field_name = 'entry_%s' % (i,)
		print("<>")
		print(self.cleaned_data)
		print("<>")
		while self.cleaned_data.get(field_name):
			# print(dict(field_name))
			entry = self.cleaned_data[field_name]
			if entry in entries:
				self.add_error(field_name, 'Duplicate')
			else:
				entries.append(entry)
			i += 1
			field_name = 'entry_%s' % (i,)
		self.cleaned_data["entries"] = entries
		scores = []
		i = 1
		f = 'score_%s' % (i,)
		while self.cleaned_data.get(f):
			score = self.cleaned_data[f]
			if score in scores:
				self.add_error(f, 'Duplicate')
			else:
				scores.append(score)
			i += 1
			f = 'score_%s' % (i,)
		self.cleaned_data["scores"] = scores

	def save(self):
		criteria = self.instance
		criteria.feature = self.cleaned_data["feature"]
		criteria.category = self.cleaned_data["category"]
		criteria.api = self.cleaned_data["api"]
		criteria.key = self.cleaned_data["key"]
		criteria.data_source = self.cleaned_data["data_source"]
		criteria.product = self.cleaned_data["product"]
		criteria.save()
		print("-->")
		print(self.cleaned_data["entries"])
		print("<--")
		for i in range(0, len(self.cleaned_data["entries"])):
			CriteriaHelper.objects.create(
				criteria=criteria,
				entry=self.cleaned_data["entries"][i],
				score=self.cleaned_data["scores"][i]
			)
    
	def get_entries(self):
		for field_name in self.fields:
			if field_name.startswith('entry_'):
				yield self[field_name]

	def get_scores(self):
		for field_name in self.fields:
			if field_name.startswith('score_'):
				yield self[field_name]

	# def get_both(self):
	# 	ans = []
	# 	A = []
	# 	B = []
	# 	for field_name in self.fields:
	# 		if field_name.startswith('entry_'):
	# 			A.append(self[field_name])
	# 	for field_name in self.fields:
	# 		if field_name.startswith('score_'):
	# 			B.append(self[field_name])
	# 	for i in range(0, len(A)):
	# 		ans.append(A[i])
	# 		if(i+1 < len(A)):
	# 			ans.append(B[i+1])
	# 	return ans

	class Meta:
		model = Criteria
		fields = ['feature','category','product','data_source','api','key']

credit_risk/loan_admin/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from .models import Feature
from .models import Configuration
from .forms import FeatureForm
from .forms import ConfigurationForm

from django.urls import reverse
from urllib.parse import urlencode
from .forms import UploadFileForm, CriteriaForm
import sys
from .counter import *
from django.contrib import messages
# Create your views here.

def index(request):
	add = request.GET.get('add')
	form = FeatureForm()
	if(add == 'ok1'):
		messages.info(request, 'Record created successfully')
		context = {'form':form, 'add':add}
	else:
		context = {'form':form}
	return render(request, 'loan_admin/index.html', context)

def configuration(request):
	add = request.GET.get('add1')
	form = ConfigurationForm()
	if(add == 'ok2'):
		messages.info(request, 'Record created successfully')
		context = {'form':form, 'add':add}
	else:
		context = {'form':form}
	return render(request, 'loan_admin/configuration.html', context)

@require_POST
def addFeature(request):
	form = FeatureForm(request.POST)
	url = reverse('loan_admin:index') 
	if form.is_valid():
		feature = form.save()
		base_url = reverse('loan_admin:index')
		query_string =  urlencode({'add': 'ok1'})
		url = '{}?{}'.format(base_url, query_string)
	return redirect(url)

@require_POST
def addConfiguration(request):
	form = ConfigurationForm(request.POST)
	url = reverse('loan_admin:configuration') 
	if form.is_valid():
		feature = form.save()
		base_url = reverse('loan_admin:configuration')
		query_string =  urlencode({'add1': 'ok2'})
		url = '{}?{}'.format(base_url, query_string)
	return redirect(url)

def criteria(request):
	add = request.GET.get('add2')
	form = CriteriaForm()
	counter = Counter()
	if(add == 'ok3'):
		messages.info(request, 'Record created successfully')
		context = {'form':form, 'counter':counter, 'add':add}
	else:
		context = {'form':form, 'counter':counter}
	return render(request, 'loan_admin/criteria.html', context)

@require_POST
def addCriteria(request):
	print("----------")
	print(request.POST.get('entry_2'))
	print("----------")
	form = CriteriaForm(request.POST)
	url = reverse('loan_admin:criteria') 
	print("++++")
	if form.is_valid():
		form.clean()
		print("?????")
		form.save()
		print("*****")
		base_url = reverse('loan_admin:criteria')
		query_string =  urlencode({'add2': 'ok3'})
		url = '{}?{}'.format(base_url, query_string)
	return redirect(url)

def uploadCSV(request):
	add = request.GET.get('add3')
	form = UploadFileForm()
	if(add == 'ok4'):
		messages.info(request, 'Record created successfully')
		context = {'form':form, 'add':add}
	else:
		context = {'form':form}
	return render(request, 'loan_admin/uploadCSV.html', context)

@require_POST
def addApplicant(request):
	form = UploadFileForm(request.POST, request.FILES)
	url = reverse('loan_admin:uploadCSV')
	print(form.errors)
	print(form.is_valid(), file=sys.stderr)
	if form.is_valid():
		form.process_data(request.POST, request.FILES['file'])
		base_url = reverse('loan_admin:uploadCSV')
		query_string =  urlencode({'add3': 'ok4'})
		url = '{}?{}'.format(base_url, query_string)
	return redirect(url)

credit_risk/loan_admin/templates/loan_admin/configuration.html
{% load crispy_forms_tags %}
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<div class="container">
	<div class="row justify-content-center">
    	<div class="col-8">
			<img src="/media/credit_risk/logo.jpg">
			<a href="{% url 'login:index' %}"> Home </a>&nbsp&nbsp&nbsp
			<a href="{% url 'loan_admin:index' %}"> Add Feature </a>&nbsp &nbsp &nbsp
			<a href="{% url 'loan_admin:criteria' %}"> Criteria </a>&nbsp&nbsp&nbsp
			<a href="{% url 'loan_admin:uploadCSV' %}"> Upload Dataset </a>
			<h1> Configuration </h1>
			{% if messages %}
			<ul class="messages">
			    {% for message in messages %}
			    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			    {% endfor %}
			</ul>
			{% endif %}
			<form action="{% url 'loan_admin:weigh' %}" method="POST" role="form">
				{% csrf_token %}
				{{ form|crispy }}
			    <input type="submit" value="Submit" class="btn btn-success">
			</form>
		</div>
	</div>
</div>

credit_risk/loan_admin/templates/loan_admin/criteria.html
{% load crispy_forms_tags %}
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script>
		$(document).ready(function(){
			$('.new').on('click', function() {
                let $this = $(document.getElementById('new_entry'))
                let $th = $(document.getElementById('new_score'))
                let name = $this.attr('name')
			    let name1 = $th.attr('name')
                let n = parseInt(name.split('_')[1]) + 1
			    let n1 = parseInt(name1.split('_')[1]) + 1
                name = 'entry_' + n
			    name1 = 'score_' + n1
                $("<br><label>Criteria "+n+"</label>"+
                "<input name='"+name+"' id='new_entry' class='textinput textInput form-control'>" 
                + "<br>" +
                 "<label>Score "+n1+"</label>"+
                "<input name='"+name1+"' id='new_score' class='textinput textInput form-control'>" 
                + "<br>").insertAfter("#new_score")
                $this.off('input', arguments.callee)
			    $this.removeAttr('id')
			    $th.removeAttr('id')
			});
		});
	</script>
</head>
<div class="container">
	<div class="row justify-content-center">
    	<div class="col-8">
			<img src="/media/credit_risk/logo.jpg">
			<a href="{% url 'login:index' %}"> Home </a>&nbsp&nbsp&nbsp
			<a href="{% url 'loan_admin:index' %}"> Add Feature </a>&nbsp &nbsp &nbsp
			<a href="{% url 'loan_admin:configuration' %}"> Configuration </a>&nbsp &nbsp &nbsp
			<a href="{% url 'loan_admin:uploadCSV' %}"> Upload Dataset </a>
			<h1> Criteria </h1>
			{% if messages %}
			<ul class="messages">
			    {% for message in messages %}
			    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			    {% endfor %}
			</ul>
			{% endif %}
			<form action="{% url 'loan_admin:cri' %}" method="POST" role="form" class=".interest-list-new">
				{% csrf_token %}
				{{ form|crispy }}
				<!-- {{ form.feature }}
				{{ form.category }}
				{{ form.product }}
				{{ form.data_source }}
				{{ form.api }}
				{{ form.key }}
				{% for field in form.get_entries %}
			    	{{ field }}
				{% endfor %} -->
				
			    <input type="submit" value="Submit" class="btn btn-success">
			</form>
			<button class="new">Add Row</button>
		</div>
	</div>
</div>

credit_risk/loan_admin/templates/loan_admin/index.html
{% load crispy_forms_tags %}
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<div class="container">
	<div class="row justify-content-center">
    	<div class="col-8">
			<img src="/media/credit_risk/logo.jpg">
			<a href="{% url 'login:index' %}"> Home </a>&nbsp&nbsp&nbsp
			<a href="{% url 'loan_admin:configuration' %}"> Configuration </a>&nbsp &nbsp &nbsp
			<a href="{% url 'loan_admin:criteria' %}"> Criteria </a>&nbsp&nbsp&nbsp
			<a href="{% url 'loan_admin:uploadCSV' %}"> Upload Dataset </a>
			<h1> Add Feature </h1>
			{% if messages %}
			<ul class="messages">
			    {% for message in messages %}
			    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			    {% endfor %}
			</ul>
			{% endif %}
			<form action="{% url 'loan_admin:add' %}" method="POST" role="form">
				{% csrf_token %}
				{{ form|crispy }}
			    <input type="submit" value="Submit" class="btn btn-success">
			</form>
		</div>
	</div>
</div>

credit_risk/loan_admin/templates/loan_admin/uploadCSV.html
{% load crispy_forms_tags %}
{% load static %}
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<div class="container">
	<div class="row justify-content-center">
    	<div class="col-8">
    		<img src="/media/credit_risk/logo.jpg">
    		<a href="{% url 'login:index' %}"> Home </a>&nbsp&nbsp&nbsp
			<a href="{% url 'loan_admin:index' %}"> Add Feature </a>&nbsp &nbsp &nbsp
			<a href="{% url 'loan_admin:configuration' %}"> Configuration </a>&nbsp &nbsp &nbsp
			<a href="{% url 'loan_admin:criteria' %}"> Criteria </a>&nbsp&nbsp&nbsp
			<h1> Upload Dataset </h1>
			{% if messages %}
			<ul class="messages">
			    {% for message in messages %}
			    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			    {% endfor %}
			</ul>
			{% endif %}
			<form action="{% url 'loan_admin:addApplicant' %}" method="POST" enctype= multipart/form-data>
				{% csrf_token %}
				{{ form|crispy }}
			    <input type="submit" value="Submit" class="btn btn-success">
			</form>
		</div>
	</div>
</div>